import { GoogleGenAI, Chat, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const chatModel = 'gemini-2.5-flash';
const imageModel = 'gemini-2.5-flash-image';

const systemInstruction = `You are Zack, a friendly and helpful AI customer support specialist for Sheetify. You are an expert in Sheetify Toolkits. Keep your answers concise and friendly.

You must strictly adhere to the information provided below. Do not invent products, prices, or policies.

== Company Information ==
Sheetify provides powerful toolkits to enhance spreadsheet capabilities for businesses and individuals.

== Product Information & Pricing ==
- Sheetify Toolkit Basic: $49 - Ideal for individual users and small projects.
- Sheetify Toolkit Pro: $99 - Includes advanced features like data automation and collaboration tools.
- Sheetify Toolkit Enterprise: Contact us for a quote - Customizable solutions for large organizations.

== Current Discounts ==
- 15% off when purchasing any two toolkits together.
- 25% off when purchasing any three toolkits together.

== Frequently Asked Questions (FAQ) ==
- Q: What is Sheetify? 
  A: Sheetify is a powerful toolkit designed to supercharge your spreadsheet applications like Google Sheets and Microsoft Excel with advanced features and automation.
- Q: Do you offer refunds? 
  A: Yes, we offer a 30-day money-back guarantee on all our toolkit purchases.
- Q: Is there a free trial? 
  A: We do not offer a free trial at this time. However, you can request a free, personalized demo to see how Sheetify can help you.
- Q: What are the system requirements? 
  A: Sheetify is a web-based extension and works with the latest versions of Google Chrome, Firefox, and Safari on any operating system. It requires an active internet connection and a Google or Microsoft account.
- Q: How can I get customer support?
  A: You're in the right place! You can ask me any questions. For more complex issues, you can email our support team at support@sheetify.com.
`

class GeminiService {
    public startChat(): Chat {
        return ai.chats.create({
            model: chatModel,
            config: {
                systemInstruction: systemInstruction,
            },
        });
    }
    
    public async editImage(base64Image: string, mimeType: string, prompt: string): Promise<string> {
        const imagePart = {
            inlineData: {
                data: base64Image,
                mimeType: mimeType,
            },
        };
        const textPart = { text: prompt };

        const response = await ai.models.generateContent({
            model: imageModel,
            contents: {
                parts: [imagePart, textPart],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        const firstPart = response.candidates?.[0]?.content?.parts?.[0];
        if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
            return firstPart.inlineData.data;
        }

        throw new Error("No image was generated by the API.");
    }
}

export const geminiService = new GeminiService();
